### ISSUE TITLE
Some README.md comments

### ISSUE THREAD

**Issue by diracdeltas** [EFForg/starttls-everywhere#1]
1. In "File Format", the example JSON no longer matches the description. For instance, there is no explanation of the `tls-policies` field.
2. There is no explanation of what `*.example.com` refers to - presumably arbitrary-deep subdomains of `example.com` and `example.com` itself?
3. How does conflict resolution work if there exist conflicting policies (either tls-policies or acceptable-mxs) for `*.eff.org` and `lists.eff.org`?
4. "A user of this file format may choose to accept multiple files." - how does conflict resolution work in this case?
5. "enforce" and "log-only" appear to be mutually-exclusive values, but can domains that specify "enforce" also opt-in to logging? Or is this the default behavior? What if a domain doesn't specify the error-notification URL?
6. Can a domain specify multiple error-notification URLs? I think this would be useful.
7. Are there reasonable restrictions on the error-notification URL? Ex: should be HTTPS, same base domain as the URL that the policy applies to.
8. "The accept-pinset field references an entry in the pinsets list, which has the same format and semantics as Chrome's pinning list." - Chrome's pinning list at https://src.chromium.org/chrome/trunk/src/net/http/transport_security_state_static.json maps "static_spki_hashes" to a list of names for the hashes, not the hashes themselves (which is what "accept-spki-hashes" is). It is probably worth discussing explicitly how chain validation works - a cert is accepted if at least one of the "accept-spki-hashes" is found in the chain.
9. Chrome's pinning list now has a "bad_static_spki_hashes" value such that a cert only validates if none of these are in the chain. Is it worth adding something analagous here?

**Comment by pierky** [comment]
Hello,

I faced some of these topics in my fork of STARTTLS-Everywhere (pull request pending); it's far from being the state of the art, some aspects are not implemented yet (mostly about policy definition files distribution and validation), but maybe you want to take a look: https://github.com/pierky/starttls-everywhere

Any feedback would be much appreciated!

Pierky

**Comment by sydneyli** [comment]
Yay, issue number 1! Here are answers to these, 4 years later.
> 1. In "File Format", the example JSON no longer matches the description. For instance, there is no explanation of the `tls-policies` field.
> 2. There is no explanation of what `*.example.com` refers to - presumably arbitrary-deep subdomains of `example.com` and `example.com` itself?

Tracking both inconsistencies at #99 now. Wildcards should only match one subdomain label. 

> 3. How does conflict resolution work if there exist conflicting policies (either tls-policies or acceptable-mxs) for `*.eff.org` and `lists.eff.org`?

Policies can only be specified for FQDNs.

> 4. "A user of this file format may choose to accept multiple files." - how does conflict resolution work in this case?

(Although we've deprioritized the list-merging feature in favor of working on a master dataset for now, we're planning to continue work on this in the future.) It'd be up to the administrator to prioritize the different list upstreams/sources.

> 5. "enforce" and "log-only" appear to be mutually-exclusive values, but can domains that specify "enforce" also opt-in to logging? Or is this the default behavior? What if a domain doesn't specify the error-notification URL?
> 6. Can a domain specify multiple error-notification URLs? I think this would be useful.

If a reporting URI is specified (maybe via [TLSRPT](https://datatracker.ietf.org/doc/rfc8460/) now and not via this list), it's an opt-in to receive error reports, even for strictly enforced policies. In general, more clarification is needed re: the relationship between TLSRPT and the list's reporting URL.

> 7. Are there reasonable restrictions on the error-notification URL? Ex: should be HTTPS, same base domain as the URL that the policy applies to.

The primary purpose of the reporting URL is not to prevent malicious reports, but to identify configuration errors (which can then be verified by the receiver). For instance, mailto is okay-- and if it's the case that your mailserver's STARTTLS is not properly configured, the reports are sent anyways.

> 8. "The accept-pinset field references an entry in the pinsets list, which has the same format and semantics as Chrome's pinning list." - Chrome's pinning list at https://src.chromium.org/chrome/trunk/src/net/http/transport_security_state_static.json maps "static_spki_hashes" to a list of names for the hashes, not the hashes themselves (which is what "accept-spki-hashes" is). It is probably worth discussing explicitly how chain validation works - a cert is accepted if at least one of the "accept-spki-hashes" is found in the chain.
> 9. Chrome's pinning list now has a "bad_static_spki_hashes" value such that a cert only validates if none of these are in the chain. Is it worth adding something analagous here?

The lists' "key-pinning" fields are still underspecified, even today; removing them was discussed at some point. Moving the discussion on this to #100!

Ok, hopefully most of these have been addressed, or at the very least, if it's an open question, there's another issue for it. Closing!
