### ISSUE TITLE
Suggestion: Use NameCoin

### ISSUE THREAD

**Issue by PowerPress** [EFForg/starttls-everywhere#10]
I love this idea of utilizing Dane & DNSSEC but as you noted these issues have to be done out of band. Please consider using or adding the ability for namecoin to do the lookups. Namecoin allows anyone to cryptographic create TLD but additionally they can pin certificates under identities that is available to anyone who downloades the client and blockchain which is exactly what you want here.

https://wiki.namecoin.info/?title=Identity

Here is an implementation doing exactly what you want:

https://github.com/okTurtles/dnschain

**Comment by azet** [comment]
We want tech. people are actually using these days (with DANE that's already a problem, but deployment is increasing). Unless there's a huge spike in NameCoin usage I don't see this as a feature in this project anywhere soon.
