### ISSUE TITLE
Remove pinsets (prev: Discuss and clarify key-pinning mechanism)

### ISSUE THREAD

**Issue by sydneyli** [EFForg/starttls-everywhere#100]
As @Snawoot mentions in issue #99, 
>  it doesn't clearly defines how implementer should conduct verifications and how to threat results. 
> It is not clear: can I pin end entity cert? If so, is it OK to skip PKI certification path which precedes matching pinned key?

The key-pinning in STARTTLS Everywhere has been in an odd "limbo" state for quite a while. Removing the capability entirely was discussed at some point in the past-- do we want to repeat the HPKP debacle that web faced? I can see this feature breaking more things than it solves, but it's true that without DANE, there isn't a way to pin trust in email. If we want to keep it, it's time to clarify this behavior.

**Comment by AliceWonderMiscreations** [comment]
A) Require certificate transparency
B) Plan to require certificates use "OCSP Must Staple" feature but don't enforce that yet, too many SMTP servers do not support OCSP stapling and as such can not use certificates that require it.

Honestly OCSP stapling really is the best you could require w/o DANE. In my opinion. Keypins will brick a server if it isn't easy for them to change the expected keypin in a way that quickly propagates and DNS is the only way to really do that - which is only secure with DNSSEC. And that's what DANE for TLS already does.

    dig TLSA +short _25._tcp.deviant.email.
