### ISSUE TITLE
Website Issue

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [EFForg/starttls-everywhere#105]
Right under the "Tooling" heading on this page is a link that leads to a 404 -

https://starttls-everywhere.org/policy-list/

The 404 link -

https://github.com/EFForg/starttls-everywhere/tree/master/starttls-policy and the text of the link is "starttls-policy"

**Comment by sydneyli** [comment]
Ah, thanks for reporting! Yes, the codebase was recently moved. I've filed EFForg/starttls-frontend/220 and will fix it shortly.
