### ISSUE TITLE
keyserver confusion

### ISSUE THREAD

**Issue by AliceWonderMiscreations** [EFForg/starttls-everywhere#107]
gpg --recv-key B693F33372E965D76D55368616EEA65D03326C9D

Which key server do I need to specify to retrieve the proper key? You documentation doesn't seem to specify the keyserver anywhere. Maybe it's a keyserver some distros are configured to search by default, but not mine.

**Comment by AliceWonderMiscreations** [comment]
--keyserver hkp://pool.sks-keyservers.net

is one that works if anyone else had trouble.

**Comment by sydneyli** [comment]
Oh, good point @AliceWonderMiscreations! We don't run our own keyserver, so we don't necessarily want to point people to a particular one. We should definitely put up our PGP key somewhere easily discoverable on the website, though. I opened EFForg/starttls-frontend#222 to track this.
