### ISSUE TITLE
Vagrantfile broken `synched_folder`.

### ISSUE THREAD

**Issue by cpu** [EFForg/starttls-everywhere#11]
Running a `vagrant up` with the provided Vagrantfile barfs an error:

```
Bringing machine 'sender' up with 'virtualbox' provider...
Bringing machine 'valid' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: vagrant-shared/starttls-everywhere
```

This appears to be the result of [a `config.vm.synched_folder` directive in the Vagrantfile](https://github.com/EFForg/starttls-everywhere/blob/master/Vagrantfile#L19) without a corresponding folder on disk.

Based on the name I'm guessing that it's intended to be the starttls-everywhere src? It's not clear what should be placed in `./vagrant-shared/starttls-everywhere`. It doesn't look like [`vagrant-bootstrap.sh`](https://github.com/EFForg/starttls-everywhere/blob/master/vagrant-bootstrap.sh) touches anything in `/vagrant/starttls-everywhere` so maybe the offending Vagrantfile line needs to be deleted?

**Comment by sydneyli** [comment]
No longer relevant to the current codebase. The equivalent code is located in [EFForg/starttls-policy-cli](github.com/efforg/starttls-policy-cli), though we don't have a VM setup for integration testing yet.
