### ISSUE TITLE
client is on some blacklists

### ISSUE THREAD

**Issue by keithws** [EFForg/starttls-everywhere#112]
Thank you trying to make email more secure. A difficult and noble cause to be sure!

My first attempt to check my domain with STARTTLS Everywhere failed because my servers refused the connection because the IP address, 178.128.188.40, was found on some blacklists, specifically, dul.dnsbl.sorbs.net and b.barracudacentral.org.

Getting off dul.dnsbl.sorbs.net may be difficult or impossible, but getting off b.barracudacentral.org should be pretty easy with their online removal request at barracudacentral.org.

I used the Blacklist Check on WhatIsMyIPAddress.com and it reported that IP address on three other blacklists as well.

spam.dnsbl.sorbs.net
dnsbl.spfbl.net
black.junkemailfilter.com

Please try to remove the IP address from as many blacklists as possible to increase the likelihood that an email admin will check their domain with STARTTLS Everywhere.

**Comment by sydneyli** [comment]
Thank you @keithws for letting us know! We're pausing our regular scans for the time being and will look into this shortly.

**Comment by sydneyli** [comment]
We should be already delisted from Barracuda (temporarily while they review), SORBS (for good), and junkemailfilter. I'll keep this open for the time being until we can confirm that we're off these lists.

**Comment by keithws** [comment]
No worries. Thanks again for build such a great tool! I'll definitely be recommending this.
