### ISSUE TITLE
Canonical URL in config.json returns 404

### ISSUE THREAD

**Issue by cpu** [EFForg/starttls-everywhere#12]
The [comment in config.js](https://github.com/EFForg/starttls-everywhere/blob/master/config.json#L2) with a canonical URL (https://eff.org/starttls-everywhere/config) for the latest config version returns a 404.

Is this intentional? Is there a better URL to include in the comment?

**Comment by saizai** [comment]
+1. @jsha ?

**Comment by jsha** [comment]
I should probably delete that comment. I don't yet have a canonical config anywhere, since we haven't officially launched this for prod use yet.

**Comment by sydneyli** [comment]
This exists now! Closing.
