### ISSUE TITLE
Project status/roadmap?

### ISSUE THREAD

**Issue by klausenbusk** [EFForg/starttls-everywhere#139]
Hi

I miss a roadmap or at least a quick project update. From the outside the project seems to be in limbo, there haven't been any meeting since April (https://lists.eff.org/pipermail/starttls-everywhere-devs/2019-April/000018.html) and the list was last updated in March (https://github.com/EFForg/starttls-everywhere/pull/128). So could we get a quick project update and/or a roadmap?

\- Kristian Klausen

**Comment by pipboy96** [comment]
cc @andresbase

**Comment by sydneyli** [comment]
Thanks for the interest all! I'll share a much longer update on Monday-- the short version is that we're still chugging along on making the project fully interoperable with the [MTA-STS](https://tools.ietf.org/html/rfc8461) spec.

**Comment by klausenbusk** [comment]
> Thanks for the interest all! I'll share a much longer update on Monday-- the short version is that we're still chugging along on making the project fully interoperable with the [MTA-STS](https://tools.ietf.org/html/rfc8461) spec.

ping? :)

**Comment by sydneyli** [comment]
We really only have a handful of folks (in flux, coming in and out of the project) working part-time on STARTTLS at the moment-- all of whom have been stretched a bit thin-- so estimating a timeline has been a bit difficult.

The next couple milestones are:
 * Migrating the list to integrate much better with mailservers that support MTA-STS-- that is, regularly polling for MTA-STS records that have an expiry date longer than the lists’ expected rate of update, and updating the list accordingly. The deadline for this is at the end of September.
 * Update documentation and website to reflect new expected behaviors.
 * Push for more widespread adoption of the list into clients.

Our aim is to get our MTA-STS integration landed into our backend tooling by the end of this month, and then from there, work on updating the documentation and website to reflect the new project direction, with a focus on acting as a backup list for MTA-STS discovery. We'd like to see MTA-STS itself get wider adoption, too.

Closing for now, but let me know if anyone has further questions! Happy to reply on this thread.
