### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by saizai** [EFForg/starttls-everywhere#14]
The README doesn't clearly indicate whether this is an experimental idea, or something that can currently be used by domain admins (nor clearly indicate how to do so, if yes).

Could you update to reflect the current state of things?

**Comment by bronson** [comment]
I have the same question.  Looking over the commits I'd guess it's experimental and I'm afraid activity on it has ground to a halt...?

**Comment by pde** [comment]
Definitely experimental and pre-alpha right now.  But it's actually quite close to being a releasable alpha, and we're looking into restarting dev work on it.

**Comment by pde** [comment]
It is now theoretically usable on postfix systems, but is only recommended if you would be okay with the possibility of dropping mail if one of the security policies was overly zealous.
