### ISSUE TITLE
Validation from web form complains token is expired or already used

### ISSUE THREAD

**Issue by guillemj** [EFForg/starttls-everywhere#142]
I tried to add (twice) my domain (hadrons.org) via the web form, got the email, and when visiting the URL with the token, it complained that it had either expired or already been used.

The first attempt I was kind of expecting it to have expired as it took around 4 days until I recalled to look for the validation mail in my spam box. :) But the second was within minutes.

**Comment by sydneyli** [comment]
Hey @guillemj ! Thanks for the report. It looks like your domain is queued and should be included in the next update. Feel free to follow-up with any questions to starttls-policy@eff.org -- we'll get back to you sooner there :)
