### ISSUE TITLE
PGP instructions are problematic

### ISSUE THREAD

**Issue by hannob** [EFForg/starttls-everywhere#147]
The instructions here
https://starttls-everywhere.org/policy-list/
are problematic for two reasons.

First it fetches the key from a "normal" keyserver (i.e. usually using the default within gpg). This means an attacker can poison the key by attaching a large number of bogus signatures, which has happened a few times lately to keys from prominent members of the PGP community.
I recommend downloading the key from a location you control via https.

Second the line
gpg --trusted-key 842AEA40C5BCD6E1 --verify policy.json.asc
uses a truncated 64 bit key id. It is possible (although expensive) to create a colliding key for 64 bit key ids. An attacker who is able to convince a person to import a specified key into the local keyring could use this for an attack. For this reason the 160 bit full key id / fingerprint should always be used when referencing keys.

**Comment by sydneyli** [comment]
Thanks for the report! You're right that the short code snippet is problematic for the above reasons. We'll fix it & also make it a bit more clear that we expect people to use the [update script](https://github.com/EFForg/starttls-everywhere/blob/master/scripts/update_and_verify.sh), which doesn't have these problems. I've migrated this issue to EFForg/starttls-frontend#285.
