### ISSUE TITLE
Clarify min-tls-version property

### ISSUE THREAD

**Issue by t2d** [EFForg/starttls-everywhere#17]
> If the min-tls-version property is present, sending mail to domains under this policy should fail if the sending MTA cannot negotiate a TLS version equal to or greater than the listed version. Valid values are TLSv1, TLSv1.1, and TLSv1.2.

Assume, I pin my domain with TLSv1.2. Does that mean that old MTAs which only support TLS1.0, but use starttls-everywhere cannot contact me anymore?

Would it be a good idea then to define a local property `max-tls-version` which overrides min-tls-version globally? Otherwise it feels like I'm always going to use TLS1.0 to ensure maximal connectivity.

**Comment by pde** [comment]
No, it is intended to mean that new MTAs which support TLSv1.2 should not tolerate a session that somehow negotiates v1.0.
