### ISSUE TITLE
Move main.cf security settings into the 'enhance' framework, and make them user controllable

### ISSUE THREAD

**Issue by pde** [EFForg/starttls-everywhere#29]
At the moment we set global postfix settings in `wrangle_existing_config`.  Probably those should be set and called as enhancements in the iInstaller APIs (`enhance` and `supporeted_enhancements`).

**Comment by azet** [comment]
I feel the same way. And thought about that as well. I'm OK with taking this one.

**Comment by sydneyli** [comment]
For the time being we've moved away from getting STARTTLS-E integrated into Certbot's Postfix installer as an enhancement.

The primary reason for this is that we want to decouple STARTTLS-E and MTA-STS support from Certbot, and administrators are also pretty nervous about letting Certbot touch their mailserver configurations. We're rolling it out as a separate tool, but are still exploring different options. There are also other reasons, but I'll leave it at that for now.
