### ISSUE TITLE
Generate a transport policy only

### ISSUE THREAD

**Issue by nthykier** [EFForg/starttls-everywhere#34]
Hi,

I have been interested in improving my work's outgoing mail setup to get above opportunistic encryption.  I have been loosely following starttls-everywhere and I would love to be able to use your current lists for this purpose.

What makes me hesitant is that the current tooling seems to take over the entire postfix configuration, which I doubt we would very happy with.  Notably, the particular SMTP server is not receiving mails from the internet.
- Do you have an example of how to only generate/maintain the transport map with the TLS rules?

**Comment by azet** [comment]
Hi @nthykier 

We're in the process of integrating this project with Certbot (the Let's Encrypt client), in current state this is pre-alpha software, so I would not recommend using it. In addition the transport map currently only works between Postfix MTAs above a certain version, so this won't make much sense to you, I think.

Aaron

**Comment by nthykier** [comment]
Thanks for the reply.

I am still very much interested in the "ruleset -> transport map"-generator and the "Postfix-only" requirement is not an issue for me. If needed be I am happy to consider providing patches for lowering the version requirements with limited loss of functionality (as I recall DANE support required 2.11 and we do not have that yet).  From my point of view, even without (e.g.) DANE support, a standardised ruleset maintained in collaboration is still better than maintaining it myself by hand.

While I can appreciate the Let's Encrypt part and the mangling of the other postfix configuration as a private person, it will make it a tougher pill to swallow for my management (not to mention it will fight with puppet over the configuration).  That is why I am attempting to avoid this particular feature-set.

As for this being alpha or software; in the short term, I am happy to manually pulling updates and reviewing the resulting transport map before applying it to my servers.  But even if this stopped being alpha/beta software, I doubt I would be allowed to let it steam-roll over our full postfix configuration. Though, I believe updating a transport map will be a different story. Phrased properly, I could probably convince my peers it would not be a lot different than subscribing to an external spam-list.


If we can create that minimal tool, I will attempt to convince my peers that we should use starttls-everywhere as a means to strengthening our outgoing mail-relays.

**Comment by azet** [comment]
We're happy for any patches or external programs that use these rule-sets. We may add them in a `contrib/` subdirectory. But as said: we're integrating with Certbot and in the future will possibly integrate the MTA-STS standard, once it has come to a stage where it can be implemented and deployed (see other issues).

The problem remains that these maps are currently Postfix specific :/

**Comment by nthykier** [comment]
I notice this is now doable via the `starttls-policy` script.  Thanks for implementing. :)
