### ISSUE TITLE
letsencrypt-postfix/PostfixConfigGenerator.py Not Found

### ISSUE THREAD

**Issue by 1Sara1** [EFForg/starttls-everywhere#51]
Certbot is installed, and is working fine on Ubuntu 16.04 x64.
Following the Directions:

git clone https://github.com/EFForg/starttls-everywhere
**_downloads it ok._**

cd starttls-everywhere

letsencrypt-postfix/PostfixConfigGenerator.py examples/starttls-everywhere.json /etc/postfix /etc/letsencrypt/live/YOUR.DOMAIN.EXAMPLE.COM

**Error**:
-bash: letsencrypt-postfix/PostfixConfigGenerator.py: No such file or directory

Searched everywhere on the Server, Github, and Google, cannot find:
PostfixConfigGenerator.py

**Comment by sydneyli** [comment]
Hi! Thanks for the interest. We're currently in the middle of porting part of this functionality [into Certbot](https://github.com/certbot/certbot/issues/4672), as well as stabilizing the documentation and API for this repository. Sorry about the confusion-- we're rehauling a pretty large existing codebase into something with a pretty different interface, so we'll have to be more diligent about updating the documentation where it exists.

**Comment by sydneyli** [comment]
I'm closing this issue for now and track ongoing updates to the large root README in #39.
