### ISSUE TITLE
Capitalization and comparing cert names

### ISSUE THREAD

**Issue by KwadroNaut** [EFForg/starttls-everywhere#59]
I thought domain names were case insensitive [1], so I created some test records:
turtle.chocovax.net.	300	IN	MX	5 TURTLE.CHOCOVAX.NET.
turtle.chocovax.net.	300	IN	MX	10 aspmx2.googlemail.com.
turtle.chocovax.net.	300	IN	MX	1 ASPMX.L.GOOGLE.COM.

Not sure how this website (caches?) results, but the 1 and 10 should present valid certificates, the 10 is presented as 'aspmx2.googlemail.COM.' on https://starttls-everywhere.org/results/?turtle.chocovax.net they both say 'In order for your certificate to be valid for your email domain, it should be unexpired, chain to a valid root, and one of the names on the certificate should … match the … the server’s hostname (the name of the server, as indicated by an MX record).

[1] except for DKIM txt records (and maybe others?)

**Comment by sydneyli** [comment]
Thanks for the report! You're right, and we should adhere to [this case folding spec](https://tools.ietf.org/html/rfc4343) and also make sure [punycode names](https://tools.ietf.org/html/rfc3492) work.
