### ISSUE TITLE
SPF record for starttls-everywhere.org doesn't match probe IP address

### ISSUE THREAD

**Issue by gwire** [EFForg/starttls-everywhere#62]
`starttls-everywhere.org` publishes a record restricting it to a single IP address

```
$ dig +short starttls-everywhere.org txt
"v=spf1 ip4:67.212.170.242 -all"
```

This is not the address that the probes come from, but this server identifies in HELO as `starttls-everywhere.org` thus fails the SPF HELO check ([RFC 7208](https://tools.ietf.org/html/rfc7208#section-2.3)).

Systems that normally require valid reverse DNS (which the checking IP address does not have) will sometimes fall back to an SPF HELO validation. But in the case of the probe, both fail.

```
Jun 25 20:53:22 util01 exim[12330]: 2018-06-25 20:53:21 no host name found for IP address 178.128.188.40
Jun 25 20:53:31 util01 exim[12330]: 2018-06-25 20:53:31 acl_local_auth_spf_helo: fail: Please see http://www.openspf.org/Why?id=postmaster%40starttls-everywhere.org&ip=178.128.188.40 : Reason: mechanism
```

**Comment by sydneyli** [comment]
Thanks for letting us know-- we migrated mailing services at some point and this is likely leftover cruft from then. flagging @wgreenberg!

**Comment by jgillula** [comment]
This should be fixed now--if it's still an issue, please let us know!
