### ISSUE TITLE
List signature on website points to an invalid URL

### ISSUE THREAD

**Issue by vsund** [EFForg/starttls-everywhere#64]
Hey, not sure if this is the right place to raise this issue, please redirect me somewhere if it isn't.

On https://starttls-everywhere.org/policy-list/ the link for the signature in
> The list is hosted here, and the corresponding signature is here.

points to https://dl.eff.org/starttls-everywhere/policy.jsona.asac which has two weird `a`s in it and throws a 404 not found. I guess this is expected to point to https://dl.eff.org/starttls-everywhere/policy.json.asc

**Comment by leonklingele** [comment]
The other links, https://dl.eff.org/starttls-everywhere.policy.json and https://dl.eff.org/starttls-everywhere.policy.json.asc are broken as well.

**Comment by vsund** [comment]
Ah right missed that. Yup, seems like the text links use a `.` instead of a `/`.

**Comment by sydneyli** [comment]
Thanks for the reports guys! This should be fixed in the most recent version of the site (pending a redeploy-- flagging @wgreenberg or @vbrown608), so I'll close this for now. The PGP fingerprint is wrong as well; for now, if you'd like to play around with it:

```
wget https://dl.eff.org/starttls-everywhere/policy.json
wget https://dl.eff.org/starttls-everywhere/policy.json.asc
gpg --recv-key B693F33372E965D76D55368616EEA65D03326C9D
gpg --trusted-key 842AEA40C5BCD6E1 --verify policy.json.asc
```

**Comment by vsund** [comment]
Oh good catch, didn't verify that previously. But as of now the signature seems to match. Might be already got fixed?

**Comment by lelutin** [comment]
@sydneyli I know this is closed already, but since it's on the same page and around the same region of text, I noticed that the example URLs in the grey box for both the json list and its signature file are also wrong. they show "starttls-everywhere.policy.json" instead of "starttls-everywhere/policy.json" (so . instead of / between "starttls-everywhere" and "policy".

**Comment by lelutin** [comment]
oh gah sorry I totally missed that @leonklingele had already reported that. sorry for the noise
