### ISSUE TITLE
support postscreen

### ISSUE THREAD

**Issue by robo2bobo** [EFForg/starttls-everywhere#69]
I am not sure if this is the right place to mention this, please close this issue if its not relevant.

I tried the test tool (https://www.starttls-everywhere.org/) with a few domains under my control and the report came back all wrong.

Apparently, the tool doesn't behave very well when postscreen (a feature of postfix) is enabled. Here are the relevant postscreen options that I use:

```
postscreen_blacklist_action = drop
postscreen_cache_cleanup_interval = 24h
postscreen_cache_retention_time = 30d
postscreen_command_time_limit = 10s
postscreen_greet_action = enforce
postscreen_greet_wait = 15s
postscreen_dnsbl_action = enforce
postscreen_dnsbl_threshold = 3
```

I am guessing that the long greet delay of 15 seconds, does not allow the tool the properly detect starttls.

Thank you.

**Comment by sydneyli** [comment]
Hi @robo2bobo, thanks for reporting! We're aware it's not clear where exactly issues should be reported, so this venue is perfectly fine. I've migrated this issue to EFForg/starttls-check#24 so I'll close it here.

**Comment by vbrown608** [comment]
Hi @robo2bobo . I'm taking a look at this issue (migrated to https://github.com/EFForg/starttls-backend/issues/102). Could you share the domain you're seeing this behavior with and/or the result you're getting from the scanner? If you'd prefer to share it privately you can e-mail at vivian@eff.org.

Thanks!
