### ISSUE TITLE
Allow people to test outbound STARTTLS support

### ISSUE THREAD

**Issue by gwire** [EFForg/starttls-everywhere#71]
I've seen a few instances where admins have configured STARTTLS support for inbound connections but not enabled it for outbound connections.  Outbound STARTTLS is not visible from a user perspective, and even if they have access to accounts on different servers, verification usually relies on being able to read an interpret trace headers.

It would be great if there were a tool to check outbound support, or at least some reference to this configuration issue in the faq, with a link to a tool such as [checktls.com/TestSender](https://www.checktls.com/TestSender).

**Comment by sydneyli** [comment]
Thanks @gwire! I've moved this suggestion to EFForg/starttls-check#26 :) This is more relevant for the STARTTLS checking tool-- whereas for the policy list, which is designed to be used by senders, we're primarily concerned about receivers being able to advertise STARTTLS support.
