### ISSUE TITLE
object has no attribute 'Config'

### ISSUE THREAD

**Issue by edt11x** [EFForg/starttls-everywhere#78]
It sounds like Python is mis-finding a Config.py module running Debian Sid with python2

    # code_legacy/PostfixConfigGenerator.py examples/starttls-everywhere.json /etc/postfix /etc/letsencrypt/live/YOUR.DOMAIN.EXAMPLE.COM
    Traceback (most recent call last):
      File "code_legacy/PostfixConfigGenerator.py", line 440, in <module>
        c = config.Config()
    AttributeError: 'module' object has no attribute 'Config'
    # find . -name Config.py
    #

**Comment by sydneyli** [comment]
Thanks for the report! That's from our old tool-- the tooling for this project has since been migrated to [EFForg/starttls-policy-cli](https://github.com/EFForg/starttls-policy-cli).
