### ISSUE TITLE
Needs a source license

### ISSUE THREAD

**Issue by cooperq** [EFForg/starttls-everywhere#8]
I reccomend GPL3

**Comment by azet** [comment]
Let's Encrypt uses Apache License 2.0 (though I do not completely agree with that choice - it's certainly a better one than GPLv3, which does not make a lot of sense here unless I missed something?). I'd be for MIT - but that's just a personal preference, Apache License 2.0 to be consistent with Let's Encrypt is probably the best idea. What do you guys think? @jsha @pde @dmwilcox
