### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by J0WI** [EFForg/starttls-everywhere#90]
I followed the steps in your [README.md](https://github.com/EFForg/starttls-everywhere/blob/master/starttls-policy/README.md), but the installation fails on the following step:
```
$ pip install starttls-policy
Collecting starttls-policy
  Could not find a version that satisfies the requirement starttls-policy (from versions: )
No matching distribution found for starttls-policy
```

**Comment by iammyr** [comment]
Hi @J0WI 

if you clone this repository and then run
`$ cd starttls-everywhere/starttls-policy`
`$ python setup.py install`

then you will have the tool installed (and `pip install starttls-policy` will not throw any more error)

**Comment by sydneyli** [comment]
Hi guys, thanks for checking out the project! We're currently in the very midst of migrating this code portion of the repository to [EFForg/starttls-policy-cli](https://github.com/EFForg/starttls-policy-cli) (see #92) and several other usability improvements-- I've filed EFForg/starttls-policy-cli#10 for now to track the general lack of documentation, but feel free to open a PR against it with your own suggestions.
