### ISSUE TITLE
Current postfix policy is useless

### ISSUE THREAD

**Issue by J0WI** [EFForg/starttls-everywhere#94]
The current policy generates only a `may`. `may` means 'use TLS if possible' and is already the recommend default. This does still allow downgrade and MITM attacks.

Here are some more secure options:
```
example.com verify protocols=TLSv1.2
example.edu encrypt protocols=SSLv3 #at least not unencrypted
example.net verify match=mx #certificate does not match all MX hosts
example.org dane-only protocols=TLSv1.3
```

**Comment by J0WI** [comment]
The `fingerprint` might be another secure option for self-signed hosts, but I'm not sure about the fallback (and of course it breaks if the cert changes).

**Comment by Snawoot** [comment]
This behavior was changed by #85. Now utility generates empty config because all domains in list are in `testing` mode and due to lack of fallback we can't set any enforcing policy.

Also, repo with config generator was splitted - check out latest code [here](https://github.com/EFForg/starttls-policy-cli/).

**Comment by J0WI** [comment]
Well, this sound even more useless.
Why are hosts, that have been successfully submitted on https://starttls-everywhere.org/ not enforced?
I think major hosts that have stable TLS support (like the `gmail.com` in the example) can also be enforced.

**Comment by Snawoot** [comment]
@J0WI I'm afraid even google doesn't indicate readiness for enforcement. At least via MTA-STS: https://mta-sts.gmail.com/.well-known/mta-sts.txt

About domains submitted via site - good question, I'd like to hear answer too.

**Comment by J0WI** [comment]
We had the same problem at HTTPS Everywhere. At the beginning only a minority of sites used HTTPS by default (also Google search) and we had to actively redirect them. Now most sites implemented a redirect on their own side.

**Comment by Snawoot** [comment]
Current policy will be meaningful and usable via Early Adopter mode as soon as [this PR](https://github.com/EFForg/starttls-policy-cli/pull/24) will be merged.

**Comment by Snawoot** [comment]
Early Adopter mode has been [merged](https://github.com/EFForg/starttls-policy-cli/pull/24). Now you may use command line option `-e` or `--early-adopter` to add testing domains in generated config. See command line help (`--help`) for details.

Probably we can consider this issue resolved for now.
