### ISSUE TITLE
"update-only" option does not exist (anymore)

### ISSUE THREAD

**Issue by J0WI** [EFForg/starttls-everywhere#95]
https://github.com/EFForg/starttls-everywhere/tree/master/starttls-policy#manually-updating-the-policy-list

**Comment by sydneyli** [comment]
Thanks @J0WI ! We're currently in the very midst of migrating this repository to [EFForg/starttls-policy-cli](https://github.com/EFForg/starttls-policy-cli) (see #92)-- I've filed EFForg/starttls-policy-cli#10 for now to track general documentation improvements, but feel free to open a PR against it with your own suggestions.
