### ISSUE TITLE
Unclear policy specification

### ISSUE THREAD

**Issue by Snawoot** [EFForg/starttls-everywhere#99]
Current specification is too vague and contradictory. For example it has [different key names](https://github.com/EFForg/starttls-everywhere/blame/master/RULES.md#L90) for actual set of policies. Most likely it's traces of recent changes.

## Outdated links

Specification refers to Chrome HSTS preload list and MTA-STS policy as starting point for understanding policy format, but links are outdated: first one is not accessible anymore, second is outdated because points to draft of recently accepted standard.

## Key pinning

Most important: it doesn't clearly defines how implementer should conduct verifications and how to threat results. For example, `pin` defined as follows:

> Should match a key of pinsets in the higher-level config. For a given pinset, a certificate for this mail domain should be accepted if at least one of the static_spki_hashes SPKIs is found in the trust chain.

Site sheds light:

> We also accept requests to pin intermediate certificate public keys. Although this option gives operators flexibility in trust, key pinning carries higher risks of breakage and is more difficult to do correctly. As such, these requests will be judged on a case-by-case basis.

It is not clear: can I pin end entity cert? If so, is it OK to skip  PKI certification path which precedes matching pinned key?

## MTA-STS

> mta-sts
> 
> Default: false
> 
> If set, then senders should expect this recipient domain to support MTA-STS.

What sender should do with his expectations? Especially, what sender should do with domains which included into STARTTLS-E list, but having `mode: none` MTA-STS policy? Why STARTTLS-E list has to interfere with MTA-STS or DANE at all?

I think it can use some polish.

**Comment by sydneyli** [comment]
There's another contradiction as to what wildcard `mx` entries. refer to. [RULES](https://github.com/EFForg/starttls-everywhere/blob/master/RULES.md#mxs) says arbitrarily many subdomain levels, but [POLICY_LIST](https://github.com/EFForg/starttls-everywhere/blob/master/POLICY_LIST.md#submitting-your-domain-to-the-list) says only one! To disambiguate, wildcards should only match **a single subdomain level** (i.e. the entire left label).
